Rewrite templates as yaml forms to improve clarity
ubuntu/aad-auth pull request #262
Opened 2023-06-19 11:12 UTC by denisonbarbosa

With https://github.com/canonical/desktop-engineering/pull/2, we defined some yaml forms to be used as issue templates for reporting bugs and requesting features on GitHub.
This provides a better and more defined way for users to interact with us and provide us with the relevant information we need to solve the problem

2023-06-19 11:14 UTC, denisonbarbosa commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +labels: ""
Should we prefix the title with something and/or add a "bug" label?

2023-06-19 12:04 UTC, didrocks requested changes
Good idea!

Can you modify https://github.com/canonical/desktop-engineering/blob/main/project-repo/templates/common/.github/ISSUE_TEMPLATE/bug_report.md too (and same for feature requests), and merge any additions that were made there here too? So that we really follow the same template and content?

2023-06-22 16:05 UTC, didrocks requested changes
I think one that one, the throubleshooting guide is fine. We just need to tell to paste the logs.

2023-06-22 16:05 UTC, didrocks commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +        * Distribution version: (**VERSION_ID** on `/etc/os-release`):
same here than adsys, tell to paste the logs?

2023-06-22 16:05 UTC, didrocks commented on .github/ISSUE_TEMPLATE/feature_request.yml
> +        * Distribution version: (**VERSION_ID** on `/etc/os-release`):
same here than adsys, tell to paste the logs?

2023-06-28 10:46 UTC, denisonbarbosa commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +        Please look at our [Troubleshooting guide](../#troubleshooting) and provide logs for the PAM and NSS modules.
Yeah, it works. I've already tested it on https://github.com/denisonbarbosa/testing-issue-template.

2023-06-29 12:58 UTC, didrocks approved these changes

2023-06-29 15:14 UTC, denisonbarbosa commented
Since this has no impact at all on the tests, I'll merge it without the tests passing while I handle the CI fails.

2023-06-29 15:14 UTC, merged