Adapting nss integration tests
ubuntu/aad-auth pull request #59
Opened 2022-09-05 19:53 UTC by denisonbarbosa

Adapting the tests to fit in the new NSS C library.

2022-09-07 13:05 UTC, didrocks requested changes
Some small comments, but overall, this is great!

Please double check again that all previous tests cases are still covered with the refactoring, I saw at least that those one are not: try to list by name or uid in group and passwd without access to shadow.

Also, we discussed on MM about listing the group. I doubt this is a buffer issue, we can check together.

2022-09-07 13:05 UTC, didrocks commented on nss/aad-auth/helper_test.go
> +	out, err = exec.Command("pkg-config", "--libs", "glib-2.0").CombinedOutput()
You can combine that in one call (cflags and ldflags). Add also `nss`

2022-09-07 13:05 UTC, didrocks commented on nss/aad-auth/helper_test.go
> +	execPath = filepath.Join(tmpDir, "aad_auth")
The name of the binary is `aad-auth`. Let’s not add another naming convention :)

2022-09-07 13:05 UTC, didrocks commented on nss/aad-auth/helper_test.go
> +	tmp, err := os.ReadDir("../")
maybe we could use `filepath.Glob()`? (Also, look at my comment about moving the dangerous C override file :))

2022-09-07 13:08 UTC, denisonbarbosa commented on .github/workflows/qa.yaml
> +          cd ./nss && make libnss_aad.so.2
Thanks for the tip! I suck when it comes to Makefile and make, that's why I use cmake instead hahaha

2022-09-08 15:13 UTC, didrocks approved these changes
All comments are resolved! Good work, it’s reassuring to have integration tests back!

2022-09-08 16:03 UTC, merged